In [2]:
import pandas as pd
import numpy as np

In [ ]:
'''
1. Logistic Regression 
2. FeedForwards Neural Networks and GPUs 
3. Convolutional Neural Networks and Reset 
4. Generating images with DC GAN's
5. Convolutional Network and ResNet 
6. Training a CNN on the CIFAR10 Dataset 
7. Regularization 
8. Improving Model with ResNet and Transfer Learning.
9. Last Topic will be Gneerative Adversarials Networks.
10.  Matric Multplication and High School Mathematics , Python 
'''

In [ ]:
# Generating Models - Real world Project using Ml

In [3]:
!pip install jovian --upgrade -q

     |████████████████████████████████| 68 kB 2.8 MB/s 


# **Pytorch**

In [4]:
import torch

In [8]:
t1  = torch.tensor(4.)
t1

tensor(4.)

In [10]:
t1.dtype

torch.float32

In [11]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [12]:
t2.dtype

torch.float32

In [13]:
# Matrix or a 2 Dimensional Tensor 
t3 = torch.tensor([[5., 6], [7,8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [14]:
t3.dtype

torch.float32

In [15]:
# 3 dimensional Arrat 

t4 = torch.tensor([[[1,2,3,4], [5,6,7,8]], 
                   [[9,10,11,12], [13,14,15,16]]])
t4.shape

torch.Size([2, 2, 4])

In [16]:
t3.shape

torch.Size([3, 2])

In [ ]:
'''

Arthemetic Operations 
y = w * x + b

'''

In [ ]:
# To compute the derivative we can compute the Backward function 
# y.backward() - Automatic Derivatives 

In [ ]:
# Display the Gradients 
print('dy/dx', x.grad)
print('dy/dw', y.grad)
print('dy/dw', w grad)
'''
dy/dw = W 
dy/db = 1
grad - Gradient Short Form.../

'''

In [2]:
import torch
t6 = torch.full((3,2), 42)

In [3]:
# Torch Concatenate - concatenate the two tensors with Compatible shapes 
t7 = torch.cat((t3, t6))
t7 

In [ ]:
# convert the numpy array to a torch tensor 

In [ ]:
# AutoGrads: The ability to autoatically compute the gradients for tensor operations is essential for training deep learning Models.
# GPU Support: While working with Massive dataset and large models, Pytorch tensor operations can be performed efficiently using a GPU. Computations that might typically take hours can be completed within minutes using GPUS.


In [4]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 68 kB 2.9 MB/s 


In [5]:
import jovian 

In [7]:
jovian.commit(project='01-pytorch-basics-live')

[jovian] Detected Colab notebook...


[jovian] Error: jovian.commit doesn't work on Colab unless the notebook was created and executed from Jovian.
Make sure to run the first code cell at the top after executing from Jovian.
Alternatively, you can download this notebook and upload it manually to Jovian.
Learn more: https://jovian.ai/docs/user-guide/run.html#run-on-colab


# **Gradient Descent and Pytorch**

In [ ]:
'''
Introductiom To Linear Regression: we will design a linear Algo that predicts crop yields for apples and oranges based on several variables.
Humidity, Temperature, Rainfall - Input Variables.
'''

In [ ]:
# yield_apple = w11 * temp + w12 * rainfall + w13 * humidity + b1 
# yield_orange = w21 * temp + w22 * rainfall + w23*humidity + b2

In [8]:
import numpy as np 
import torch

In [ ]:
# We will adjust the weight by using the technique called as Gradient Descent - Which is the heart of Deep learning


In [14]:
inputs = np.array(
    [[73, 67, 43],
    [91,88,64],
    [102, 43, 37],
    [69, 96, 70]]
, dtype='float32')

In [ ]:
# Now Basically Converting the PyTorch Arrays into the tensors 

In [16]:
input = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


NameError: ignored

In [10]:
# Weights and Biasis
w = torch.randn(2 , 3, requires_grad = True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.3230, -0.6591, -0.0507],
        [-0.3216, -0.4686,  0.3696]], requires_grad=True)
tensor([-0.2492, -0.4896], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t() + b
# @ is matrix multiplication in PyTorch and .t method return the transpose of a tensor.

In [19]:
# MSE Loss 
def mse(t1, t2):
  diff = t1 - t2 
  return torch.sum(diff * diff) / diff.numel()

In [ ]:
# Computer Gradients 
print(b)
print(b.grad)

In [ ]:
# Increasing the wight element value slighly will incfease the loss 
# Decreasing the weight element value slighlt will decrease the loss

In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [ ]:
# Loss - >  MSE 
preds = model(input)
loss = mse(preds, targets)
print(loss)

In [20]:
'''
Before we proceed, we reset the gradient to zero by invoking the .zer0_() method. We need to do this because the PyTorch accumulates gradients. 
Otherwise, the next time we invoke.backwards on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

'''
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

AttributeError: ignored

In [ ]:
### Training the Model using Gradient Descent 


In [ ]:

preds = model(inputs)
# Generate the Predictions
print(preds)

# Step 2: Calculate the Loss 
loss = mse(preds, targets)
print(loss)

# Compute Gradients 
loss.backward()
print(w.grad)
print(b.grad)


In [21]:
# Adjust the Weights and Reset the Gradients 
print(w)
print(b)

tensor([[-0.3230, -0.6591, -0.0507],
        [-0.3216, -0.4686,  0.3696]], requires_grad=True)
tensor([-0.2492, -0.4896], requires_grad=True)


In [ ]:
pred = model(inputs)
loss = mse(preds, targets)
print(loss)

In [ ]:
# Train the model for Multiple Epochs 
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# Calculate the Loss 
preds = model(inputs)
loss = mse(pred, targets)
print(loss)

In [ ]:
targets 

Linear Regression using PyTorch built-ins 

In [ ]:
'''
We have implemented linear Regression and Gradient Descent model using some basic tesnor operations. Howeverm since this is a common pattern in deep learning. PyTorch provides several buil-in functions 
and classes to make it easy to create and train models with just a few lines of code.

Numpy does not support GPUS but PyTorch Does
'''

In [25]:
input = np.array([[73., 67, 43], [91, 88, 64], [87,134, 58], [73., 67, 43], [91, 88, 64], [87,134, 58]])
input.shape

(6, 3)

In [26]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(input, targets)
train_ds[0: 3]

In [ ]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

In [27]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [ ]:
# Define Model 
model == nn.linear(3, 2)
print(model.weight) # Creates the Weight Matrix
print(model.bias)   # Creates the Bias Matrix

In [ ]:
# Parameters 
list(model.parameters())

In [28]:
# Generate Predictions 
preds = model(inputs)
preds

In [ ]:
'''
model.weight
model.bias
'''

In [ ]:
# Layered Model which has Parameters Inside it 
preds = models(input)


In [ ]:
# Can import MSE loss at Torch 
import torch.nn.functional as F 
# nn.functional package contains many useful functions and severalOther Utilities 

In [ ]:
# Define Loss Function 
loss_fn = F.mse_loss

In [ ]:
# Once we have define the loss function we can now work upon the Gradient Descent to further Optimize the Algorithm 
opt = torch.optim.SGD(model.parameters(), lr = 1e-5) # Stochastic Gradient Descent 
# lr is the Learning Rate and Parameters are the loss and weight matrices
# Learning Rate - so we take the small Steps not the Big Steps

# **Utility Function **

In [ ]:
# Utility Function to train the Model 
def fit(num_epochs, model, loss_fn,opt, train_dl ):
  # Repeat for the number of Epochs 
  for epoch in range(num_epochs):

    # Train with the Batch of Datas
    for xa,xb in train_dl:

      # Generating the Prediction 
      pred = model(xb)

      # Calculate the Loss
      loss = loss_fn(pred, yb) 

      # Compute the Gradients 
      loss.backward()

      # Upgrade the Parameters using Gradients 
      opt.step()

      # Reset the Gradient to Zero 
      opt.zero_grad()
      
      if(epoch + 1) % 10 == 0:
        print("Epochs [{}/ {}], loss: {:4f}".format(epoch +1, num_epochs, loss.item()))


      return

In [ ]:
fit(100, model, loss_fn, opt, train_dl)

In [ ]:
# Compare with Target 


In [ ]:
model(torch.tensor([75, 64, 23.]))

In [29]:
### Machine Learning and Classical Programming

In [ ]:
### Explanation

In [ ]:
# Images - Logistic Regression # Feed Forward Networks # Convolutional Neural Network 

In [ ]:
# ResNet,Regularization and Data Augmentation 

In [ ]:
# Generative Models 